name: Deploy to VPS

on:
  push:
    branches:
      - main # Sesuaikan dengan branch utama Anda

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            # Bersihkan folder tujuan agar tidak crash saat clone
            sudo rm -rf /var/www/dev-nurhealth
            sudo mkdir -p /var/www/dev-nurhealth
            sudo chown -R $USER:$USER /var/www/dev-nurhealth
            cd /var/www/dev-nurhealth
            
            # Clone repo public (tanda titik '.' sangat penting)
            git clone https://github.com/dafa21/webb.git .
            
            # Instalasi & Build
            npm install
            npm run build
            
            # Pastikan PM2 terinstal untuk menjaga aplikasi tetap jalan
            sudo npm install -g pm2 || true
            
            # Restart aplikasi lewat PM2 dengan Port 30002
            pm2 delete dev-nurhealth || true
            NODE_ENV=production PORT=30002 pm2 start "npm run dev" --name "dev-nurhealth"
            pm2 save
